# Generated by Django 5.0.6 on 2024-06-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id_alimento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=10)),
                ('energia_kcal', models.IntegerField(default=0)),
                ('energia_kj', models.IntegerField(default=0)),
                ('agua_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('proteinas_totales_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('proteinas_vegetales_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('proteinas_animal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grasa_total_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohidratos_totales_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohidratos_disponibles_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fibra_dietaria_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cenizas_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calcio_mg', models.IntegerField(default=0)),
                ('fosforo_mg', models.IntegerField(default=0)),
                ('zinc_mg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hierro_mg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('caroteno_equivalentes_totales_ug', models.IntegerField(default=0)),
                ('vitaminaA_equivalentes_totales_ug', models.IntegerField(default=0)),
                ('tiamina_mg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('riboflavina_mg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('niacina_mg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vitaminaC_mg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('acido_folico_ug', models.IntegerField(default=0)),
                ('sodio_mg', models.IntegerField(default=0)),
                ('potasio_mg', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Alimentos',
            },
        ),
    ]
