# Generated by Django 5.0.6 on 2024-06-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPDYA_BACKEND', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alimento',
            new_name='Alimentos',
        ),
    ]
